import { useMemo, useState } from 'react';
import { realProductCatalog } from '../catalog';
import { DollViewer, ItemThumbnail } from './DollViewer';
import { useTravel } from './TravelContext';
import type { Category, StudioRoute } from './types';
import './studio.css';

const categories: Category[] = ['top','bottom','outerwear','shoes','accessory'];
const labels: Record<Category,string> = { top:'Tops',bottom:'Bottoms',outerwear:'Layers',shoes:'Shoes',accessory:'Accessories' };

function StyleStage() {
  const { destination, equippedOutfit, wardrobeItems, equip, surprise, navigate } = useTravel();
  const matchCount = Object.values(equippedOutfit).filter((id) => { const item=wardrobeItems.find((entry)=>entry.id===id); return item && (item.weatherTag==='any'||item.weatherTag===destination.weather); }).length;
  return <section className="studio-style"><aside><div className="studio-forecast"><small>{destination.city} forecast</small><strong>{destination.forecast}</strong><span>{matchCount}/{categories.length} pieces match today</span></div><DollViewer/><button className="studio-surprise" onClick={surprise}>Surprise me</button></aside><div className="studio-wardrobe"><header><p>Destination closet</p><h1>Dress for {destination.city}</h1><span>Destination exclusives appear first. Every choice snaps perfectly onto the doll.</span></header>{categories.map((category,index)=>{const items=wardrobeItems.filter((item)=>item.category===category).sort((a,b)=>Number(b.destinationTags.includes(destination.id))-Number(a.destinationTags.includes(destination.id)));return <details open={index===0} key={category}><summary><b>{String(index+1).padStart(2,'0')}</b><strong>{labels[category]}</strong><span>{items.length} choices</span></summary><div className="studio-items">{items.map((item)=><button key={item.id} aria-pressed={equippedOutfit[category]===item.id} onClick={()=>equip(category,item.id)}><ItemThumbnail item={item}/>{item.destinationTags.includes(destination.id)&&<i>{destination.city}</i>}<strong>{item.name}</strong><small>{item.weatherTag==='any'?'Everyday':`${item.weatherTag} weather`}</small></button>)}</div></details>})}<button className="studio-primary" onClick={()=>navigate('explore')}>Lock in look & explore</button></div></section>;
}

function ExploreStage() {
  const { destination, collectedStickers, collect, navigate } = useTravel(); const collected=collectedStickers[destination.id]??[]; const [flash,setFlash]=useState(false); const [position,setPosition]=useState(8);
  const snap=(id:string)=>{collect(id);setFlash(true);setTimeout(()=>setFlash(false),380)};
  return <section className="studio-explore"><header><p>Photo safari</p><h1>Explore {destination.city}</h1><span>Move your traveler, find all {destination.hotspots.length} clues, and take a picture.</span></header><div className={`safari-scene scene-${destination.scene} ${flash?'is-flashing':''}`} style={{'--accent':destination.accent} as React.CSSProperties}><div className="safari-skyline"/><div className="safari-avatar" style={{left:`${position}%`}}><DollViewer compact/></div>{destination.hotspots.map((spot)=><button className="safari-hotspot" style={{left:`${spot.x}%`,top:`${spot.y}%`}} aria-pressed={collected.includes(spot.id)} onClick={()=>snap(spot.id)} key={spot.id}><span>{collected.includes(spot.id)?'Saved':'Photo'}</span><strong>{spot.label}</strong></button>)}<div className="camera-flash"/></div><div className="safari-controls"><button onClick={()=>setPosition(Math.max(2,position-12))}>Walk left</button><span>{collected.length}/{destination.hotspots.length} stickers collected</span><button onClick={()=>setPosition(Math.min(82,position+12))}>Walk right</button></div><button className="studio-primary" disabled={collected.length<destination.hotspots.length} onClick={()=>navigate('journal')}>{collected.length<destination.hotspots.length?'Find every photo clue':'Open my travel journal'}</button></section>;
}

function JournalStage() {
  const { destinations, destination, collectedStickers, passportStamps, stampDestination, navigate, equippedOutfit, wardrobeItems }=useTravel(); const stickers=collectedStickers[destination.id]??[]; const canStamp=stickers.length===destination.hotspots.length; const outfitNames=Object.values(equippedOutfit).map(id=>wardrobeItems.find(item=>item.id===id)?.name).filter(Boolean);
  return <section className="studio-journal"><header><p>Travel journal & passport</p><h1>My adventure book</h1><span>{passportStamps.length}/{destinations.length} destinations stamped</span></header><div className="journal-layout"><article className="journal-postcard" style={{'--accent':destination.accent} as React.CSSProperties}><div><small>Postcard from</small><h2>{destination.city}</h2><p>In {destination.city}, I wore my {outfitNames[0]} and collected {stickers.length} photo safari stickers.</p><div>{destination.hotspots.map(spot=><span className={stickers.includes(spot.id)?'is-earned':''} key={spot.id}>{spot.label}</span>)}</div></div><DollViewer compact/></article><section className="passport-book"><div><small>Little Jetter passport</small><strong>{passportStamps.length} journeys complete</strong></div><div className="passport-slots">{destinations.map((place,index)=><span className={passportStamps.includes(place.id)?'is-stamped':''} style={{'--stamp':place.accent} as React.CSSProperties} key={place.id}><b>{String(index+1).padStart(2,'0')}</b>{place.city}</span>)}</div><button disabled={!canStamp||passportStamps.includes(destination.id)} onClick={stampDestination}>{passportStamps.includes(destination.id)?'Passport stamped':canStamp?`Stamp ${destination.city}`:'Complete the photo safari first'}</button></section></div><button className="studio-primary" onClick={()=>navigate('shop')}>Visit the Souvenir Closet</button></section>;
}

function ShopStage() {
  const { equippedOutfit, wardrobeItems }=useTravel(); const [answer,setAnswer]=useState(''); const [unlocked,setUnlocked]=useState(false); const matchedIds=Object.values(equippedOutfit).map(id=>wardrobeItems.find(item=>item.id===id)?.ltkAffiliateId).filter(Boolean); const products=useMemo(()=>realProductCatalog.slice(0,18),[]);
  return <section className="studio-shop"><header><p>For grown-ups later</p><h1>Souvenir Closet</h1><span>Real-world matches inspired by the finished game look. No prices or checkout for kids.</span></header><div className="souvenir-grid">{products.map(product=><article className={matchedIds.includes(product.id)?'is-match':''} key={product.id}><img src={product.imageUrl} alt=""/><small>{matchedIds.includes(product.id)?'Favorited match':product.brand}</small><strong>{product.name}</strong></article>)}</div><aside className="parent-gate"><h2>Parent gate</h2>{unlocked?<p>Grown-up view unlocked. Verified shopping links can be connected here.</p>:<form onSubmit={event=>{event.preventDefault();if(answer==='12')setUnlocked(true)}}><label>Grown-ups: what is 7 + 5?</label><input value={answer} onChange={event=>setAnswer(event.target.value)} inputMode="numeric"/><button>Unlock parent view</button></form>}</aside></section>;
}

export function StudioApp(){const {route,navigate,destinations,destination,setDestination,passportStamps}=useTravel(); const routes:StudioRoute[]=['style','explore','journal','shop'];return <div className="studio-app"><header className="studio-header"><a href="/">Little Jetter</a><select aria-label="Active destination" value={destination.id} onChange={event=>setDestination(event.target.value)}>{destinations.map(place=><option value={place.id} key={place.id}>{place.city}, {place.country}</option>)}</select><span>{passportStamps.length}/{destinations.length} stamps</span></header><nav className="studio-nav">{routes.map((item,index)=><button className={route===item?'is-active':''} onClick={()=>navigate(item)} key={item}><span>{String(index+1).padStart(2,'0')}</span>{item==='shop'?'Souvenir Closet':item}</button>)}</nav><main>{route==='style'?<StyleStage/>:route==='explore'?<ExploreStage/>:route==='journal'?<JournalStage/>:<ShopStage/>}</main></div>}
