// Manual catalog for the 128 clip-art clothing pieces extracted from
// "Clip 1 .png" (scripts/clipart-extract/batch1/items/item-NNN.png).
// category: which dressUpCatalog.json bucket + slot value.
// anchor: which positioning preset to use (see position-clipart.mjs).
export const CLIPART_ITEMS = [
  { i: 0, id: 'little-jetter-logo-tee', name: 'Little Jetter logo tee', category: 'tops', anchor: 'top' },
  { i: 1, id: 'navy-stripe-heart-tee', name: 'Navy stripe heart tee', category: 'tops', anchor: 'top' },
  { i: 2, id: 'cherry-tee', name: 'Cherry tee', category: 'tops', anchor: 'top' },
  { i: 3, id: 'globe-tee', name: 'Globe tee', category: 'tops', anchor: 'top' },
  { i: 4, id: 'rainbow-tee', name: 'Rainbow tee', category: 'tops', anchor: 'top' },
  { i: 5, id: 'floral-puff-sleeve-top', name: 'Floral puff-sleeve top', category: 'tops', anchor: 'top' },
  { i: 6, id: 'denim-jacket-classic', name: 'Classic denim jacket', category: 'layers', anchor: 'outerwear' },
  { i: 7, id: 'pink-bow-cardigan', name: 'Pink bow cardigan', category: 'layers', anchor: 'outerwear' },
  { i: 8, id: 'cream-cable-cardigan', name: 'Cream cable cardigan', category: 'layers', anchor: 'outerwear' },
  { i: 9, id: 'blue-airplane-hoodie', name: 'Blue airplane hoodie', category: 'layers', anchor: 'outerwear' },
  { i: 10, id: 'olive-heart-jacket', name: 'Olive heart jacket', category: 'layers', anchor: 'outerwear' },
  { i: 11, id: 'pink-wrap-coat', name: 'Pink wrap coat', category: 'layers', anchor: 'outerwear' },
  { i: 12, id: 'blue-daisy-dress', name: 'Blue daisy dress', category: "tops", anchor: "dress", style: 'dress' },
  { i: 13, id: 'pink-bow-dress', name: 'Pink bow dress', category: "tops", anchor: "dress", style: 'dress' },
  { i: 14, id: 'yellow-daisy-dress', name: 'Yellow daisy dress', category: "tops", anchor: "dress", style: 'dress' },
  { i: 15, id: 'denim-heart-overalls-dress', name: 'Denim heart overalls dress', category: "tops", anchor: "dress", style: 'dress' },
  { i: 16, id: 'olive-belted-romper', name: 'Olive belted romper', category: "tops", anchor: "dress", style: 'dress' },
  { i: 17, id: 'pink-button-romper', name: 'Pink button romper', category: "tops", anchor: "dress", style: 'dress' },
  { i: 18, id: 'cream-button-romper', name: 'Cream button romper', category: "tops", anchor: "dress", style: 'dress' },
  { i: 19, id: 'blue-stripe-dress', name: 'Blue stripe dress', category: "tops", anchor: "dress", style: 'dress' },
  { i: 20, id: 'pink-floral-puff-dress', name: 'Pink floral puff dress', category: "tops", anchor: "dress", style: 'dress' },
  { i: 21, id: 'lavender-tiered-dress', name: 'Lavender tiered dress', category: "tops", anchor: "dress", style: 'dress' },
  { i: 22, id: 'black-pinafore-dress', name: 'Black pinafore dress', category: "tops", anchor: "dress", style: 'dress' },
  { i: 23, id: 'red-gingham-dress', name: 'Red gingham dress', category: "tops", anchor: "dress", style: 'dress' },
  { i: 24, id: 'explore-hoodie', name: 'Explore hoodie', category: 'layers', anchor: 'outerwear' },
  { i: 25, id: 'jet-set-hoodie', name: 'Jet Set hoodie', category: 'layers', anchor: 'outerwear' },
  { i: 26, id: 'pink-heart-hoodie', name: 'Pink heart hoodie', category: 'layers', anchor: 'outerwear' },
  { i: 27, id: 'colorblock-jacket', name: 'Colorblock jacket', category: 'layers', anchor: 'outerwear' },
  { i: 28, id: 'brown-sherpa-jacket', name: 'Brown sherpa jacket', category: 'layers', anchor: 'outerwear' },
  { i: 29, id: 'denim-sherpa-collar-jacket', name: 'Denim sherpa-collar jacket', category: 'layers', anchor: 'outerwear' },
  { i: 30, id: 'black-moto-jacket', name: 'Black moto jacket', category: 'layers', anchor: 'outerwear' },
  { i: 31, id: 'cream-cherry-cardigan', name: 'Cream cherry cardigan', category: 'layers', anchor: 'outerwear' },
  { i: 32, id: 'red-heart-cardigan', name: 'Red heart cardigan', category: 'layers', anchor: 'outerwear' },
  { i: 33, id: 'navy-stripe-cardigan', name: 'Navy stripe cardigan', category: 'layers', anchor: 'outerwear' },
  { i: 34, id: 'cream-bow-blouse', name: 'Cream bow blouse', category: 'tops', anchor: 'top' },
  { i: 35, id: 'denim-heart-capris', name: 'Denim heart capris', category: 'bottoms', anchor: 'bottom' },
  { i: 36, id: 'pink-cargo-shorts', name: 'Pink cargo shorts', category: 'bottoms', anchor: 'bottom' },
  { i: 37, id: 'olive-cargo-shorts', name: 'Olive cargo shorts', category: 'bottoms', anchor: 'bottom' },
  { i: 38, id: 'khaki-cargo-shorts', name: 'Khaki cargo shorts', category: 'bottoms', anchor: 'bottom' },
  { i: 39, id: 'denim-daisy-shorts', name: 'Denim daisy shorts', category: 'bottoms', anchor: 'bottom' },
  { i: 40, id: 'cream-drawstring-shorts', name: 'Cream drawstring shorts', category: 'bottoms', anchor: 'bottom' },
  { i: 41, id: 'pink-tiered-skirt', name: 'Pink tiered skirt', category: 'bottoms', anchor: 'bottom' },
  { i: 42, id: 'blue-pleated-skirt', name: 'Blue pleated skirt', category: 'bottoms', anchor: 'bottom' },
  { i: 43, id: 'khaki-pleated-skirt', name: 'Khaki pleated skirt', category: 'bottoms', anchor: 'bottom' },
  { i: 44, id: 'green-plaid-skirt', name: 'Green plaid skirt', category: 'bottoms', anchor: 'bottom' },
  { i: 45, id: 'black-tiered-skirt', name: 'Black tiered skirt', category: 'bottoms', anchor: 'bottom' },
  { i: 46, id: 'cream-bow-shorts', name: 'Cream bow shorts', category: 'bottoms', anchor: 'bottom' },
  { i: 47, id: 'pink-sport-shorts', name: 'Pink sport shorts', category: 'bottoms', anchor: 'bottom' },
  { i: 48, id: 'cherry-pajama-set', name: 'Cherry pajama set', category: "tops", anchor: "dress", style: 'pajama' },
  { i: 49, id: 'blue-cloud-pajama-set', name: 'Blue cloud pajama set', category: "tops", anchor: "dress", style: 'pajama' },
  { i: 50, id: 'teddy-bear-set', name: 'Teddy bear set', category: "tops", anchor: "dress", style: 'pajama' },
  { i: 51, id: 'good-places-set', name: '"Good Places" set', category: "tops", anchor: "dress", style: 'pajama' },
  { i: 52, id: 'daisy-purple-set', name: 'Daisy purple set', category: "tops", anchor: "dress", style: 'pajama' },
  { i: 53, id: 'travel-cream-set', name: '"Travel" cream set', category: "tops", anchor: "dress", style: 'pajama' },
  { i: 54, id: 'sage-tank-set', name: 'Sage tank set', category: "tops", anchor: "dress", style: 'pajama' },
  { i: 55, id: 'blue-airplane-set', name: 'Blue airplane set', category: "tops", anchor: "dress", style: 'pajama' },
  { i: 56, id: 'car-print-set', name: 'Car-print set', category: "tops", anchor: "dress", style: 'pajama' },
  { i: 57, id: 'moon-star-set', name: 'Moon and star set', category: "tops", anchor: "dress", style: 'pajama' },
  { i: 58, id: 'heart-print-set', name: 'Heart-print set', category: "tops", anchor: "dress", style: 'pajama' },
  { i: 59, id: 'turtle-print-set', name: 'Turtle-print set', category: "tops", anchor: "dress", style: 'pajama' },
  { i: 60, id: 'navy-stripe-swimsuit', name: 'Navy stripe swimsuit', category: "tops", anchor: "dress", style: 'swim' },
  { i: 61, id: 'pink-floral-swim-onesie', name: 'Pink floral swim onesie', category: "tops", anchor: "dress", style: 'swim' },
  { i: 62, id: 'pink-ruffle-swimsuit', name: 'Pink ruffle swimsuit', category: "tops", anchor: "dress", style: 'swim' },
  { i: 63, id: 'navy-swim-shorts', name: 'Navy swim shorts', category: 'bottoms', anchor: 'bottom' },
  { i: 64, id: 'green-floral-swim-shorts', name: 'Green floral swim shorts', category: 'bottoms', anchor: 'bottom' },
  { i: 65, id: 'yellow-daisy-swim-shorts', name: 'Yellow daisy swim shorts', category: 'bottoms', anchor: 'bottom' },
  { i: 66, id: 'navy-airplane-romper', name: 'Navy airplane romper', category: "tops", anchor: "dress", style: 'swim' },
  { i: 67, id: 'pink-daisy-onesie', name: 'Pink daisy onesie', category: "tops", anchor: "dress", style: 'swim' },
  { i: 68, id: 'sage-onesie', name: 'Sage onesie', category: "tops", anchor: "dress", style: 'swim' },
  { i: 69, id: 'blue-gingham-swimsuit', name: 'Blue gingham swimsuit', category: "tops", anchor: "dress", style: 'swim' },
  { i: 70, id: 'pink-floral-swim-wrap', name: 'Pink floral swim wrap', category: "tops", anchor: "dress", style: 'swim' },
  { i: 71, id: 'green-floral-swim-set', name: 'Green floral swim set', category: "tops", anchor: "dress", style: 'swim' },
  { i: 72, id: 'yellow-puffer-jacket', name: 'Yellow puffer jacket', category: 'layers', anchor: 'outerwear' },
  { i: 73, id: 'pink-puffer-jacket', name: 'Pink puffer jacket', category: 'layers', anchor: 'outerwear' },
  { i: 74, id: 'blue-cloud-puffer-jacket', name: 'Blue cloud puffer jacket', category: 'layers', anchor: 'outerwear' },
  { i: 75, id: 'olive-puffer-jacket', name: 'Olive puffer jacket', category: 'layers', anchor: 'outerwear' },
  { i: 76, id: 'cream-sherpa-hood-puffer', name: 'Cream sherpa-hood puffer', category: 'layers', anchor: 'outerwear' },
  { i: 77, id: 'pink-floral-swim-briefs', name: 'Pink floral swim briefs', category: 'bottoms', anchor: 'bottom' },
  { i: 78, id: 'purple-heart-puffer-jacket', name: 'Purple heart puffer jacket', category: 'layers', anchor: 'outerwear' },
  { i: 79, id: 'navy-puffer-jacket', name: 'Navy puffer jacket', category: 'layers', anchor: 'outerwear' },
  { i: 80, id: 'brown-bear-hood-puffer', name: 'Brown bear-hood puffer', category: 'layers', anchor: 'outerwear' },
  { i: 81, id: 'panda-hood-puffer', name: 'Panda-hood puffer', category: 'layers', anchor: 'outerwear' },
  { i: 82, id: 'red-fox-hood-puffer', name: 'Red fox-hood puffer', category: 'layers', anchor: 'outerwear' },
  { i: 83, id: 'olive-dino-hood-puffer', name: 'Olive dino-hood puffer', category: 'layers', anchor: 'outerwear' },
  { i: 84, id: 'pink-floral-swim-bottoms', name: 'Pink floral swim bottoms', category: 'bottoms', anchor: 'bottom' },
  { i: 85, id: 'pink-bear-hood-puffer', name: 'Pink bear-hood puffer', category: 'layers', anchor: 'outerwear' },
  { i: 86, id: 'straw-sun-hat-clip', name: 'Straw sun hat (clip art)', category: "accessories", anchor: "hat" },
  { i: 87, id: 'pink-sun-hat', name: 'Pink sun hat', category: "accessories", anchor: "hat" },
  { i: 88, id: 'cream-daisy-bucket-hat', name: 'Cream daisy bucket hat', category: "accessories", anchor: "hat" },
  { i: 89, id: 'navy-airplane-cap', name: 'Navy airplane cap', category: "accessories", anchor: "hat" },
  { i: 90, id: 'green-explore-cap', name: 'Green explore cap', category: "accessories", anchor: "hat" },
  { i: 91, id: 'pink-heart-cap', name: 'Pink heart cap', category: "accessories", anchor: "hat" },
  { i: 92, id: 'navy-pompom-beanie', name: 'Navy pompom beanie', category: "accessories", anchor: "hat" },
  { i: 93, id: 'cream-pompom-beanie', name: 'Cream pompom beanie', category: "accessories", anchor: "hat" },
  { i: 94, id: 'red-pompom-beanie', name: 'Red pompom beanie', category: "accessories", anchor: "hat" },
  { i: 95, id: 'olive-pompom-beanie', name: 'Olive pompom beanie', category: "accessories", anchor: "hat" },
  { i: 96, id: 'olive-trapper-hat', name: 'Olive trapper hat', category: "accessories", anchor: "hat" },
  { i: 97, id: 'cream-trapper-hat', name: 'Cream trapper hat', category: "accessories", anchor: "hat" },
  { i: 98, id: 'blue-daisy-bucket-hat', name: 'Blue daisy bucket hat', category: "accessories", anchor: "hat" },
  { i: 99, id: 'pink-heart-sunglasses', name: 'Pink heart sunglasses', category: 'accessories', anchor: 'face' },
  { i: 100, id: 'pink-heart-sunglasses-2', name: 'Pink heart sunglasses (rose)', category: 'accessories', anchor: 'face' },
  { i: 101, id: 'round-brown-sunglasses', name: 'Round brown sunglasses', category: 'accessories', anchor: 'face' },
  { i: 102, id: 'round-brown-sunglasses-2', name: 'Round brown sunglasses (tan)', category: 'accessories', anchor: 'face' },
  { i: 103, id: 'flower-red-sunglasses', name: 'Flower red sunglasses', category: 'accessories', anchor: 'face' },
  { i: 104, id: 'flower-red-sunglasses-2', name: 'Flower red sunglasses (pink)', category: 'accessories', anchor: 'face' },
  { i: 105, id: 'cream-bow-headband', name: 'Cream bow headband', category: "accessories", anchor: "hat" },
  { i: 106, id: 'pink-hair-bow', name: 'Pink hair bow', category: "accessories", anchor: "hat" },
  { i: 107, id: 'blue-scrunchie', name: 'Blue scrunchie', category: "accessories", anchor: "hat" },
  { i: 108, id: 'green-scrunchie', name: 'Green scrunchie', category: "accessories", anchor: "hat" },
  { i: 109, id: 'floral-headscarf', name: 'Floral headscarf', category: "accessories", anchor: "hat" },
  { i: 110, id: 'pink-backpack', name: 'Pink backpack', category: 'accessories', anchor: 'bag', file: 'item-110a.png' },
  { i: 110, id: 'pink-daisy-rain-boots', name: 'Pink daisy rain boots', category: 'shoes', anchor: 'shoes', file: 'item-110b.png' },
  { i: 111, id: 'green-backpack', name: 'Green backpack', category: 'accessories', anchor: 'bag' },
  { i: 112, id: 'little-jetter-tote-bag', name: 'Little Jetter tote bag', category: 'accessories', anchor: 'bag' },
  { i: 113, id: 'brown-satchel-bag', name: 'Brown satchel bag', category: 'accessories', anchor: 'bag' },
  { i: 114, id: 'yellow-fanny-pack', name: 'Yellow fanny pack', category: 'accessories', anchor: 'bag' },
  { i: 115, id: 'white-heart-sneakers', name: 'White heart sneakers', category: 'shoes', anchor: 'shoes' },
  { i: 116, id: 'yellow-daisy-rain-boots', name: 'Yellow daisy rain boots', category: 'shoes', anchor: 'shoes' },
  { i: 117, id: 'blue-suitcase', name: 'Blue suitcase', category: 'accessories', anchor: 'bag' },
  { i: 118, id: 'pink-sneakers', name: 'Pink sneakers', category: 'shoes', anchor: 'shoes' },
  { i: 119, id: 'navy-sneakers', name: 'Navy sneakers', category: 'shoes', anchor: 'shoes' },
  { i: 120, id: 'brown-strap-sandals', name: 'Brown strap sandals', category: 'shoes', anchor: 'shoes' },
  { i: 121, id: 'pink-mary-janes-clip', name: 'Pink mary janes', category: 'shoes', anchor: 'shoes' },
  { i: 122, id: 'black-mary-janes-clip', name: 'Black mary janes', category: 'shoes', anchor: 'shoes' },
  { i: 123, id: 'brown-buckle-sandals', name: 'Brown buckle sandals', category: 'shoes', anchor: 'shoes' },
  { i: 124, id: 'green-sneakers', name: 'Green sneakers', category: 'shoes', anchor: 'shoes' },
  { i: 125, id: 'red-hiking-boots', name: 'Red hiking boots', category: 'shoes', anchor: 'shoes' },
  { i: 126, id: 'tan-hiking-boots', name: 'Tan hiking boots', category: 'shoes', anchor: 'shoes' },
  { i: 127, id: 'blue-strap-sandals', name: 'Blue strap sandals', category: 'shoes', anchor: 'shoes' },
];
