// Real-product references (LTK affiliate picks) live in
// src/data/realProducts.ts, generated by scripts/build-real-products.mjs
// from scripts/_ltk-import.csv plus the original hand-picked entries. This
// file just re-exports so existing imports (`from './catalog'`) keep
// working.
export type { ProductCategory, RealProductReference } from './data/realProducts';
export { realProductCatalog } from './data/realProducts';
